### ISSUE TITLE
BXL & Bradant overlaped

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#107]
There is an overlap between both regions. 
It is true that Bradant has a special shape
https://fr.wikipedia.org/wiki/Province_du_Brabant_flamand
![image](https://user-images.githubusercontent.com/11535234/117114984-c78f0e00-ad8c-11eb-87bd-5211415cb737.png)

![image](https://user-images.githubusercontent.com/11535234/117113583-f60be980-ad8a-11eb-8301-202de84a8fbb.png)

**Comment by tjbtjbtjb** [comment]
What the point ? Do you want to include the "Reǵion de Bruxelles-Capitale" into another one in the geo module ? Does it appear like that in data ?

**Comment by odadoun** [comment]
As you can see BXL region can't be seen . And BXL the number are very high.I guess it should be appear like this 
<img width="522" alt="image" src="https://user-images.githubusercontent.com/11535234/117116917-366d6680-ad8f-11eb-8f40-7457bcb5b4ec.png">
May be a substraction BXL region to Bradant will be enough .. don't you think ?

**Comment by odadoun** [comment]
I will fixe it for bokeh since in folium it is ok
<img width="536" alt="image" src="https://user-images.githubusercontent.com/11535234/117128037-2e1c2800-ad9d-11eb-81fa-3ee062a9e7fb.png">
