### ISSUE TITLE
GBR json missing subregion

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#108]
it seems that not all the subregion is present in the JSON file.
For instance this
Cornwall and Isles of Scilly code E06000052
Do have any idea how we should update the json ?

**Comment by tjbtjbtjb** [comment]
Dear Jean-François,

  Thanks for the suggestion. The issue should have been closed. It was solved with the couple of data  https://opendata.arcgis.com/datasets/3a4fa2ce68f642e399b4de07643eeed3_0.geojson and http://geoportal1-ons.opendata.arcgis.com/datasets/0c3a9643cc7c4015bb80751aad1d2594_0.csv, the latest defining the regions of England. 
  
  Then we got a quite nice map for GBR now. We unfortunatly still have missing covid19 data for some region (outside England). But the geo information is ok. 
  
![image](https://user-images.githubusercontent.com/6871008/119886516-5a0d7200-bf33-11eb-8353-cf809851f950.png)

  Cheers,

Tristan
