### ISSUE TITLE
Warning with population_subregion

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#118]
When spf is loaded this warning appears:

/Users/dadoun/Programs/Python/coa-project/coabook/../pycoa/coa/geo.py:811: FutureWarning: The default value of regex will change from True to False in a future version.
  pop_fra['population_subregion']=pop_fra['Population municipale'].str.replace(r"[ \xa0]","").astype(int)
/Users/dadoun/Programs/Python/coa-project/coabook/../pycoa/coa/geo.py:811: FutureWarning: The default value of regex will change from True to False in a future version.
  pop_fra['population_subregion']=pop_fra['Population municipale'].str.replace(r"[ \xa0]","").astype(int)

**Comment by tjbtjbtjb** [comment]
Still don't know what should be done ! :\

**Comment by tjbtjbtjb** [comment]
Problem solved somehow…
