### ISSUE TITLE
front.get with what='daily' output='pandas' does not provide a 'daily' field…

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#12]
See screenshot
![Screenshot from 2020-11-22 12-01-55](https://user-images.githubusercontent.com/6871008/99902075-6a5e3f00-2cbb-11eb-8d66-e10b7d0d73c5.png)

**Comment by tjbtjbtjb** [comment]
And the 'cumul' field is meaningless.

**Comment by tjbtjbtjb** [comment]
done isn't it ?

**Comment by coa-project** [comment]
seems to be fixed

**Comment by tjbtjbtjb** [comment]
Fixed I guess.
