### ISSUE TITLE
Problem with GeoManager ?

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#124]
I am wondering if this is correct:

reg=['Asia','Africa','North America','South America','Europe','Australia']
print([cg.GeoManager('name').get_GeoRegion().is_region(i) for i in reg])
return:
['Asia', 'Africa', 'North America', 'South America', 'Europe', False]
False should be 'Australia'
isn't it ?

**Comment by tjbtjbtjb** [comment]
Not at all.
Australia is not a region, it is a country. Then it returns "false".
If the input is a country, it returns the standardized name. Example: 
![image](https://user-images.githubusercontent.com/6871008/144273065-568986f9-fcde-4c5e-a28a-4c5116ff8e51.png)
