### ISSUE TITLE
strange bump owid total_case worldwide 

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#131]
A=cf.plot(which="total_cases",what='daily',option=['sumall'])
Why this bump 12/10/2021 ? Artefact ? fillnan pb but it seems not ...
<img width="861" alt="image" src="https://user-images.githubusercontent.com/11535234/147553361-0d68b48e-784d-4454-a555-4aac1dd1526f.png">

**Comment by tjbtjbtjb** [comment]
Probably real data.
