### ISSUE TITLE
geo problem with 'España peninsular' ?

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#132]
Can you please have a look:
where= 'España peninsular' seems to give all Spain including islands ...
but could be a display pb ... thanks

**Comment by tjbtjbtjb** [comment]
Finally not a geo pbl. Closing issue.

**Comment by odadoun** [comment]
please have look into

>f=cg.GeoCountry('ESP')
>A=f.get_data()
>f.get_subregions_from_list_of_region_names(['España peninsular'],output='name')
it gives:
[...,'Santa Cruz de Tenerife'...]
and it shouln't. Or may be I don't use it correctly

**Comment by tjbtjbtjb** [comment]
Well… not in my version… 

![image](https://user-images.githubusercontent.com/6871008/147690361-eaade869-8278-49ea-a3e8-da853b8ef534.png)

Furthermore, why do you need `A=f.get_data()` in your code ?

**Comment by odadoun** [comment]
Sorry I d'ont use get_data() in the code.
By the way geo from main or fram dev you are using ?
