### ISSUE TITLE
"widht_height" Vs  "plot_height" Vs "plot_width"  => Nothing work....

### ISSUE THREAD

**Issue by flobe1** [coa-project/pycoa#133]
Bonjour,

Tout d'abord, je tiens à vous féliciter pour votre travail, c'est excellent et en plus fait par des français !
C'est suffisamment rare, pour le souligner et en plus cela semble vraiment d'actualité et nécessaire, donc bravo.
Le code, son hébergement, le fait qu'il soit opnesource, .... Vraiment Bravo.
Et comme 'est fait par des français, autant parler en français ;-) cela me change un peu...

Un peu galère pour commencer, et mettre tout en place, mais on y arrive.

Dans les exemples que vous donnez : 
`cf.plot(which='tot_dc',what='daily',option=['smooth7', 'sumall'],when='01/01/2020:',title='DC par semaine')`
J'ai une jolie courbe => Nickel
![image](https://user-images.githubusercontent.com/34690378/147667888-16e3961c-45f8-4698-aa5f-f732107d90e5.png)

Mais, étant un peu brimé par la dimension, je cherche à augmenter la taille du graphique.
Je cherche et je trouve dans Courbes (https://github.com/coa-project/pycoa/wiki/Courbes#personnaliser-les-graphiques) : 
`plot_width=300,plot_height=300`

Donc, je fais l'essai et boum ERROR !
`cf.plot(which='tot_dc',what='daily',option=['smooth7', 'sumall'],when='01/01/2020:',title='DC par semaine',plot_width=600,plot_height=400)`

![image](https://user-images.githubusercontent.com/34690378/147668073-aa28671e-3586-45c7-a3f9-ea05ea026ec7.png)

---------------------
CoaKeyError                               Traceback (most recent call last)
<ipython-input-44-61bdb2aeaa9a> in <module>
----> 1 cf.plot(which='tot_dc',what='daily',option=['smooth7', 'sumall'],when='01/01/2020:',title='DC par semaine',plot_width=600,plot_height=400)

~/.local/lib/python3.9/site-packages/coa/front.py in generic_plot(**kwargs)
    396 
    397         """
--> 398         kwargs_test(kwargs, ['where', 'what', 'which', 'whom', 'when',
    399                              'input', 'input_field', '**width_height'**, 'title', 'option','typeofplot'],
    400                     'Bad args used in the pycoa.plot() function.')

~/.local/lib/python3.9/site-packages/coa/tools.py in kwargs_test(given_args, expected_args, error_string)
    114     bad_kwargs=[a for a in list(given_args.keys()) if a not in expected_args ]
    115     if len(bad_kwargs) != 0 :
--> 116         raise CoaKeyError(error_string+' Unrecognized args are '+str(bad_kwargs)+'.')
    117 
    118     return True

**CoaKeyError: "Bad args used in the pycoa.plot() function. Unrecognized args are ['plot_width', 'plot_height']."**
---------------------

Bon, ok, je vois bien que plot_height et plot_width ne fonctionnent pas, mais que dans les arguments on a maintenant 'width_height'.

OK, un petit tour dans le code de front.py.
Ligne 384 :  width_height : width and height of the picture .
Ligne 385:  If specified should be a list of width and height. For instance width_height=[400,500]

Donc, petit essai :+1: 
`cf.plot(which='tot_dc',what='daily',option=['smooth7', 'sumall'],when='01/01/2020:',title='DC par semaine',width_height=[400,600])`
![image](https://user-images.githubusercontent.com/34690378/147668624-74e20baa-3637-4b79-afdb-33c881a9dab3.png)

---------------------------
CoaKeyError                               Traceback (most recent call last)
<ipython-input-42-b920aa046312> in <module>
----> 1 cf.plot(which='tot_dc',what='daily',option=['smooth7', 'sumall'],when='01/01/2020:',title='DC par semaine',width_height=[400,600])

~/.local/lib/python3.9/site-packages/coa/front.py in generic_plot(**kwargs)
    418             kwargs = {}
    419         elif input_arg == None:
--> 420             t = get(**kwargs, output='pandas')
    421             which = kwargs.get('which', listwhich()[0])
    422             what = kwargs.get('what', listwhat()[0])

~/.local/lib/python3.9/site-packages/coa/front.py in get(**kwargs)
    278                 See listoption().
    279     """
--> 280     kwargs_test(kwargs, ['where', 'what', 'which', 'whom', 'when', 'output', 'option', 'bins', 'title', 'visu', 'tile','dateslider','maplabel'],
    281                 'Bad args used in the pycoa.get() function.')
    282     # no dateslider currently

~/.local/lib/python3.9/site-packages/coa/tools.py in kwargs_test(given_args, expected_args, error_string)
    114     bad_kwargs=[a for a in list(given_args.keys()) if a not in expected_args ]
    115     if len(bad_kwargs) != 0 :
--> 116         raise CoaKeyError(error_string+' Unrecognized args are '+str(bad_kwargs)+'.')
    117 
    118     return True

CoaKeyError: "Bad args used in the pycoa.get() function. Unrecognized args are ['width_height']."
---------------------------

Une idée ?

Cordialement,
Et merci pour tout votre travail, encore une fois.

;-)

**Comment by odadoun** [comment]
Jolie ! Chapeau pour l'installation ! c'était pas trop compliqué ?
Bravo pour le bug ! je viens de fixer.
Fais un `git pull`
et relance le kernel du notebook. 
Pour les maps c'est mieux d'avoir : plot_width = plot_height

Sinon tu travailles sur la version 'main' qui est censé être stable.
Pour info il existe la version dev moins stable mais avec plus de fonctionnalités.
Encore merci de ton intérêt ca fait plaisir 
A+

**Comment by odadoun** [comment]
je ferme l'issue n'hesite pas à réouvrir si ca marche tjs pas !

**Comment by flobe1** [comment]
Merci,
J'ai commencé Python ce matin, alors découverte....
Je confirme c'est réglé.
![image](https://user-images.githubusercontent.com/34690378/147694115-b8c8e664-7653-43f0-92b8-9f00eba3260b.png)

**Comment by odadoun** [comment]
Non ce matin ? et ton niveau en info quel est-il ? 
Sinon je t'ai confondu avec quelqu'un qui nous a contacté hier sur twitter ...
Comment as-tu eu écho de pycoa ? 
Sinon pour avoir les info en France au niveau national utilise plutôtla base spfnational:
Tu fais un cf.setwhom('spfnational')
a+

**Comment by flobe1** [comment]
**"Non ce matin ? et ton niveau en info quel est-il ?"**
Oui, ce matin ~ 9h.
Niveau informatique : Ingé en mécanique, mais j'ai bossé dans une ancienne entreprise nationale dans les communications (FT qui est devenue une couleur ;-) ). Je gérais le fonctionnement et le développement continue des applications/services sur tout le réseau FR. Full GNU/Linux, 3 sites d’hébergements, langages (php, java, javascript, bash, C, perl, python, css, markdown,  hadoop, ...).

**"Comment as-tu eu écho de pycoa ?"**
Chemin un peu bizarre, mais au regard de la situation, je fais mes propres statistiques.
Je suis "tombé" sur PyCoA en récupérant des infos sur https://www.data.gouv.fr/fr/reuses/pycoa-python-covid-analysis/

**"Sinon pour avoir les info en France au niveau national utilise plutôt la base spfnational:
Tu fais un cf.setwhom('spfnational')"**
Déjà regardé, mais pas top.
J'ai laissé un second bug, impossible de mettre deux jeux de données sur un même graphique.

Et comme je t'ai sous la main, je souhaite aller un peu plus loin et arriver à un truc comme : 
https://tinyurl.com/stats-covid-france

Site original : https://i-technology.net/stats-covid-france/
L'outil est pas top pour moi, PowerBI je l'ai vu naître, et grandir et il garde toujours les mêmes défauts.

**Comment by odadoun** [comment]
>https://tinyurl.com/stats-covid-france 
Oui ! on songe aussi à faire un dashboard avec pycoa.
Regarde sur le web dashboard + bokeh (la lib python utilisée dans pycoa)
