### ISSUE TITLE
Superposition de deux valeurs épidémiologique

### ISSUE THREAD

**Issue by flobe1** [coa-project/pycoa#134]
Bonjour,
Mon souhait étant d'avoir plusieurs courbes sur un même graphique, je me reporte sur l'exemple (voir lien ci-dessous)
https://github.com/coa-project/pycoa/wiki/Avance#superposition-de-deux-valeurs-%C3%A9pid%C3%A9miologiques-%C3%A0-partir-dun-exemple
![image](https://user-images.githubusercontent.com/34690378/147700574-2cc837d2-9340-4f5b-875e-35666d649bbe.png)

Et boum, ERRORs
![image](https://user-images.githubusercontent.com/34690378/147700685-1790e63c-13fc-47f6-b095-b3f5ba6c6d51.png)

Serait-il possible : 
- De résoudre ce bug,
- D'expliquer un peu le code ?

Autant je comprend : 
`A=cf.get(which='cur_hosp',where=['22','13'])`  => Récupérer les 'cur_hosp' dans les départements '22' et '13'
`B=cf.get(which='tot_P',where=['22','13']) ` => Récupérer les 'tot_P' dans les départements '22' et '13'

Mais
`A['tot_P']=B['tot_P'] ` => ????
`cf.plot(input=A,input_field=['cur_hosp','tot_P']) `=> ????

**Comment by odadoun** [comment]
houla que de bug.
Peux-tu refaire un git pull
et relance le noyau je viens de fixer le bug

**Comment by flobe1** [comment]
OK, maintenant on peut mettre plusieurs courbes.
Comment, et pourquoi, je verrai
Mais LOL la dimension ne marche pas...

**Comment by odadoun** [comment]
houla oui c'est un peu le bordel + un bug dans la legend
Je crois que ce soucis est fixé avec la prochaine version.
En attendant mieux vaut comparer que 2 courbes

**Comment by flobe1** [comment]
OK,
Tant pis pour les dimensions.
Comment ajouter une troisième courbes ?

![image](https://user-images.githubusercontent.com/34690378/147709122-9328435d-ed93-425a-a1f4-e1fa7d706207.png)

**Comment by odadoun** [comment]
pareil.
Par exemple:

A=cf.get(which='cur_hosp',where='13')
B=cf.get(which='tot_T',where='13')
C=cf.get(which='tot_vacc2',where='13')
A['tot_T']=B['tot_T']
A['tot_vacc2']=C['tot_vacc2']
cf.plot(input=A,input_field=['tot_T','cur_hosp','tot_vacc2'])

**Comment by odadoun** [comment]
refais un pull j'ai fixé le bug de la legend

**Comment by flobe1** [comment]
Ok, je commence à comprendre les les combinaisons de données.

![image](https://user-images.githubusercontent.com/34690378/147709777-ac432b95-0393-41c6-a593-e29f705f8e23.png)


Bon allez, il est tard, il faut dormir et c'est les vacances....
Un dernier bug pour la route ?

![image](https://user-images.githubusercontent.com/34690378/147709822-72ec211e-7a42-4c22-a76d-fda88f9b0c2f.png)

**Comment by odadoun** [comment]
Oui ! c'est avec la version  dev.
Si tu as le courage. Tu passes directe à la dev ;)
C'est ici que ca se passe 
https://github.com/coa-project/pycoa/tree/dev

**Comment by flobe1** [comment]
Fait

**Comment by flobe1** [comment]
Par contre, je vois souvent ces erreurs
/geo.py:513: ShapelyDeprecationWarning:

![image](https://user-images.githubusercontent.com/34690378/147710187-2475e353-d382-44ba-b2d5-226a143bd96e.png)

**Comment by flobe1** [comment]
Du coup, 4 courbes c'est encore mieux.
![image](https://user-images.githubusercontent.com/34690378/147710384-c35fed6e-d927-4697-92a7-e515a1f2329b.png)

Mais parfois les graphiques sont incohérents...
Même code, affichage différent...

![image](https://user-images.githubusercontent.com/34690378/147710431-ccc27741-ec3a-4f17-951b-1f06b1eca9c8.png)

**Comment by odadoun** [comment]
Regarde si ce n'est 0as une différence en linéaire et log de l'axe y. Change au niveau de l'onglet sur le graphique

**Comment by flobe1** [comment]
Si tout à fait :+1:
