### ISSUE TITLE
Open question: does geo should be call from the front ?

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#136]
maybe the user should have the opportunity to call some geo method inside the front ...
for instance listwhere('europe') to retrieve the country list of EU ...
or listwhere('Île-de-France') ...

**Comment by tjbtjbtjb** [comment]
It's not an easy way… but the information is available within the `front` framework. Have a look to the following lines of code (with worldwide db selected) : 

![image](https://user-images.githubusercontent.com/6871008/150431847-9a6ca50a-b224-45c3-ab54-c6bff514171e.png)
