### ISSUE TITLE
set_dense_geometry for France

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#139]
it will be nice if when set_dense_geometry  is used to have IDF outside France Metropolitaine
![image](https://user-images.githubusercontent.com/11535234/158749571-d6e7ffa8-be57-46a7-996c-8bc39a56a9e5.png)

**Comment by tjbtjbtjb** [comment]
This feature was implemented and then… suppressed for some (good ?) reasons … 
I don't know what to do…

**Comment by odadoun** [comment]
May be we can have 2 levels of condensed:
-condensed & extracondensed with IDF outside Métro ?

**Comment by tjbtjbtjb** [comment]
The code is ready to have a zoomed copy of "Grand Paris", not full IdF. 
You would like a copy ? a move ? full or not full IdF (full is rather large) ?

**Comment by odadoun** [comment]
when one used spark for all french departement this is what we get:
If we can move IDF/ Grand Paris with a small zoom could be wonderful 
![image](https://user-images.githubusercontent.com/11535234/158764784-c9f623d0-9af1-4266-a7d0-c424a5a8fb3e.png)
