### ISSUE TITLE
No axis name for yearly plots ?

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#149]
When loading mpfront, the yearly plot does not provide plots with x-axis names.
![image](https://user-images.githubusercontent.com/6871008/171507215-fc7bb463-5ef3-49b6-a31c-ef6fb0aa532c.png)

**Comment by tjbtjbtjb** [comment]
Same problem with other db, if there's less than 1 year of data. 
![image](https://user-images.githubusercontent.com/6871008/212877659-f50ab10e-b3f0-45d2-8d28-0be954676183.png)

**Comment by odadoun** [comment]
done !
