### ISSUE TITLE
Taiwan behaviour for jhu and owid

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#158]

**Comment by odadoun** [comment]
I think there is a bug on Geo
===============
geo=cg.GeoManager('name')
geo.set_standard('iso3')
B=(geo.to_standard('World',output='list',db='jhu',interpret_region=True))
print('TWN' in B)
is False 

Taiwan aka TWN is not return by geo  
============

**Comment by tjbtjbtjb** [comment]
Well, the status of Taiwan is politically complex. Since the begining of pycoa, we're using as a ref the country list from UN to avoid any polytical dilemna : https://unstats.un.org/unsd/methodology/m49/ . And Taiwan does not appear in it, actually.
