### ISSUE TITLE
The new front doesnot manage properly the getwhom() function

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#161]
See : 

![image](https://user-images.githubusercontent.com/6871008/177993258-f224db4c-3307-4031-a952-9bacef1c027e.png)

**Comment by odadoun** [comment]
fixed

**Comment by tjbtjbtjb** [comment]
When the `setwhom` has not been set, one cannot get the `listwhom()` output, whereas one should want to know available db.
![image](https://user-images.githubusercontent.com/6871008/178098226-c8d8838a-ed73-4a13-9651-f13cd1f8d8c2.png)

Moreover, the error when using the `listwhere()`, `listwhich()` and so on are not properly managed.

**Comment by odadoun** [comment]
Very good point ! 
fixed

**Comment by tjbtjbtjb** [comment]
But `listwhere()`, `listwhich()` `list***()` are incorrect. Because `getwhom()` answers by default `jhu` and one would wait for correct answers…

![image](https://user-images.githubusercontent.com/6871008/178098584-e1f09789-e7dd-4db6-8bdc-52d838d52f9a.png)

**Comment by odadoun** [comment]
I guess fixed
