### ISSUE TITLE
When using national db, cannot select the whole country with the "where" keyword

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#162]
for example, in spf
`cf.plot(where='FRA') `
does not work. 

It would be very usefull.

**Comment by odadoun** [comment]
fixed , but not fully tested...

**Comment by tjbtjbtjb** [comment]
For worldwide db, "World" is in the `pycoa.listwhere(True)`. 

But for national db, e.g. `spf`, `France` is not in the list. That is not homogeneous.

![image](https://user-images.githubusercontent.com/6871008/178113263-de584a60-073f-48d6-9280-07b9b1bb6675.png)

**Comment by odadoun** [comment]
True , done ç
