### ISSUE TITLE
installation on ubuntu problem solved on raspberry pi 400

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#164]
- pip3 install geopandas
return error due to missing error while installin fiona

- pip3 install fiona
return error due to gdal missing

- pip3 install gdal
return error since libgdal not install 
 
---> apt install libgal-dev
and after  pip3 install geopandas

this error could also appear  on os x and maybe windows

Procedure installation using setup.py must be updated !!

**Comment by tjbtjbtjb** [comment]
See https://github.com/coa-project/pycoa/issues/170
