### ISSUE TITLE
when country have been parsed by geo, country name changes sometimes

### ISSUE THREAD

**Issue by coa-project** [coa-project/pycoa#17]
I am just asking, maybe it is what we want...
For instance:
sp=jhu.get_stats(which='deaths',location=['USA','France'])
The location name 'USA' changed to 'United States'
location=='USA' can not be used ...

**Comment by tjbtjbtjb** [comment]
The location is standardized. By default, for easy readability, it's given as "names". 
USA is the ISO 3166-1 alpha-3 code, not the official name. 

For homogeneity, it could be 'USA' and 'FRA', or 'United States' and 'France'. 

We may change the standard output to iso2, iso3 or id-num, but it's much more clear to use the full name.
