### ISSUE TITLE
Cannot load SPF on lpnpycoa…

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#192]
![image](https://github.com/coa-project/pycoa/assets/6871008/ad6aa7b2-5308-414d-82d8-12a852bc4225)

**Comment by odadoun** [comment]
lpnpycoa ? does still is still true

**Comment by tjbtjbtjb** [comment]
Still true with the `main` version. Not the `readingsomething`… really needs a merge !!!

**Comment by odadoun** [comment]
ok close. We will merge the branches this week
