### ISSUE TITLE
codelocation issue on various db…

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#195]
On db \in [dgs; insee; jhu-usa; rki; shareclim] there is a codelocation issue which prevent correct access. When trying to do a plot, we've got the error : 

![image](https://github.com/coa-project/pycoa/assets/6871008/357eee86-a99e-48a0-9e72-9b60385552e6)

**Comment by odadoun** [comment]
cannot reproduce. Please give the command

**Comment by tjbtjbtjb** [comment]
It's within the main version. Under the 'readingsomething' version, it works.

**Comment by odadoun** [comment]
ok close
