### ISSUE TITLE
Cannot do a plot with the sciensano db (BrabantWallon not recognized as subregion)

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#196]
With the `sciensano` db, we've got a error with a subregion BrabantWallon when doint a 
`pycoa.plot()`
command

![image](https://github.com/coa-project/pycoa/assets/6871008/a5bff624-63e7-40f8-8912-b512d47ea311)

**Comment by odadoun** [comment]
can't reproduce, close
