### ISSUE TITLE
By default, tot_deaths should be selected for all covid19 db (if available)

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#197]
Summary : 
dgs → tot_cases (but it's the only one available)
dpc → tot_deaths
escovid19data → tot_deaths
europa → tot_deaths
govcy → tot_deaths
imed  → tot_cases ⇒ **TO BE UPDATED, tot_deaths avail.**
insee → tot_deaths_since2018
jhu → tot_deaths
jhu-usa → tot_confirmed ⇒ **TO BE UPDATED, tot_deaths avail.**
jpnmhlw → tot_deaths
moh → tot_deaths
mpoxgh → tot_deaths
owid → tot_deaths
phe → tot_deaths
risklayer → tot_positive ( tot_deaths not available)
rki → tot_deaths
sciensano → tot_hosp ( tot_deaths not available)
spf → tot_dchosp ⇒ **should be renamed ?**
spfnational → cur_reanimation ⇒ **TO BE UPDATED in tot_dc** → **but to be renamed also ?**

**Comment by odadoun** [comment]
tot_deaths for all db.

spf → tot_dchosp ⇒ should be renamed ? I don't thing so . We decided to keep the original name from DB point of view
