### ISSUE TITLE
Issue for full geographical area when using the reload mechanism

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#198]
With db `europa`, `jhu`, `owid` and `mpoxgh`, the full geographical area management is broken when using the reload mechanism. 
Example : 
![image](https://github.com/coa-project/pycoa/assets/6871008/2041f49d-2224-48fe-9057-9198dda81d08)
whereas
![image](https://github.com/coa-project/pycoa/assets/6871008/65d3df2a-20f5-4b4a-a12e-7a83c805d2f9)

**Comment by odadoun** [comment]
finally fixed ....
