### ISSUE TITLE
textcopyright, plot_width, plot_height don't work

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#205]
pycoa.plot(where='Paris',title='new title',textcopyright='new db',plot_width=300,plot_height=300)
  Bad args used in the get_stats() function. Unrecognized args are ['textcopyright', 'plot_width', 'plot_height'].  
  
  peut etre faut il les enlever de la doc.
<img width="999" alt="Capture d’écran 2024-05-02 à 10 13 11" src="https://github.com/coa-project/pycoa/assets/117040017/6d344bef-a592-41a2-866b-e1bbf04879fc">

**Comment by odadoun** [comment]
No it works, due to the modification I've done on the previous bug
