### ISSUE TITLE
guideline not working

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#209]
`pycoa.plot(where='Bretagne' ,which='tot_vacc_complet', mode='hline', title='Vacciné en Bretagne', guideline=False)`

  Bad args used in the get_stats() function. Unrecognized args are ['guideline'].  

Retirer du wiki ? 
https://github.com/coa-project/pycoa/wiki/Courbes

**Comment by coa-project** [comment]
Bug fixed !
Amazing that this guideline was not working for at least 1 year  ...
