### ISSUE TITLE
bug on setvisu()

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#218]
`pycoa.setvisu(vis='seaborn')
`
~/Desktop/pycoa/coabook/../coa/front.py in setvisu(self, **kwargs)
    102         else:
    103             self.setdisplay(vis)
--> 104             if 'output' in self.getkwargs():
    105                 self.getkwargs().pop('output')
    106             if tile :

~/Desktop/pycoa/coabook/../coa/front.py in getkwargs(self)
    435 
    436     def getkwargs(self,):
--> 437         return self._setkwargs
    438 
    439     def chartsinput_deco(f):
AttributeError: 'Front' object has no attribute '_setkwargs'

**Comment by NoamXD8** [comment]
j'ai l'impression que cela se produit quand on est deja en seaborn et quon fait setvisu(vis='seaborn') par exemple

**Comment by odadoun** [comment]
je pense que c'est reglé
