### ISSUE TITLE
bug for histo

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#219]
`pycoa.hist(typeofhist='byvalue')`

UnboundLocalError                         Traceback (most recent call last)
/var/folders/nq/h5smb_5d2pvfz0dwfj4q8czc0000gn/T/ipykernel_72176/718953392.py in <module>
      4 #pycoa.hist(typeofhist='byvalue')
      5 
----> 6 pycoa.hist(typeofhist='byvalue')

~/Desktop/pycoa/coabook/../coa/front.py in wrapper(self, **kwargs)
    616             kwargs['input'] = pandy
    617             self.setkwargs(**kwargs)
--> 618             return f(self,**kwargs)
    619         return wrapper
    620     # ----------------------------------------------------------------------

~/Desktop/pycoa/coabook/../coa/front.py in inner(self, **kwargs)
    908                 raise CoaKeyError('Unknown typeofhist value. Available value : listhist().')
    909 
--> 910             return func(self,fig)
    911         return inner
    912 

UnboundLocalError: local variable 'fig' referenced before assignment

**Comment by odadoun** [comment]
fixed
