### ISSUE TITLE
bug with bypop

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#220]
`pycoa.plot(where='France',bypop='100k')`

AttributeError                            Traceback (most recent call last)
/var/folders/nq/h5smb_5d2pvfz0dwfj4q8czc0000gn/T/ipykernel_5063/2860555406.py in <module>
----> 1 pycoa.plot(where='France',bypop='100k')

~/Desktop/pycoa/coabook/../coa/front.py in wrapper(self, **kwargs)
    499                     else:
    500                         val = _listwhat[0]
--> 501                     pandy = self._db.normbypop(pandy , val, bypop)
    502                     if bypop=='pop':
    503                         input_field = input_field+' per total population'

~/Desktop/pycoa/coabook/../coa/covid19.py in normbypop(self, pandy, val2norm, bypop)
    600         pandy = self._gi.add_field(input=pandy,field=pop_field,geofield='codelocation')
    601     else:
--> 602         if not isinstance(self._gi,coge.GeoCountry):
    603             self._gi=None
    604         else:

AttributeError: 'DataBase' object has no attribute '_gi'

**Comment by odadoun** [comment]
fixed
