### ISSUE TITLE
bug on histo byvalue bokeh

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#222]
`pycoa.hist(where='Bretagne', which='tot_vacc_complet', typeofhist='byvalue', bins=4)`

<img width="574" alt="Capture d’écran 2024-05-23 à 11 53 32" src="https://github.com/coa-project/pycoa/assets/117040017/80878e88-e87b-4faa-96aa-1e9e5af7b51b">

**Comment by odadoun** [comment]
what is your problem with this chart :-)
