### ISSUE TITLE
bug byvalue seaborn

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#224]
have a look on bokeh result
On x axis it should be value not 'where'

**Comment by NoamXD8** [comment]
that is ok ? I can remove the line and I can also reduce the number of bins if necessary 

<img width="944" alt="Capture d’écran 2024-05-27 à 16 49 48" src="https://github.com/coa-project/pycoa/assets/117040017/cad0ab2e-2566-4448-9b41-efc57c137f2f">
