### ISSUE TITLE
bug with setvisu

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#225]
`pycoa.setvisu(vis='seaborn', plot_width=600, plot_height=400)
`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/nq/h5smb_5d2pvfz0dwfj4q8czc0000gn/T/ipykernel_42992/811394035.py in <module>
----> 1 pycoa.setvisu(vis='seaborn', plot_width=600, plot_height=400)

~/Desktop/pycoa/coabook/../coa/front.py in setvisu(self, **kwargs)
    125         title = kwargs.get('title',None)
    126 
--> 127         self._cocoplot.setkwargsfront(kwargs)
    128 
    129         if vis not in self._listvisu:

AttributeError: 'NoneType' object has no attribute 'setkwargsfront'

**Comment by odadoun** [comment]
fixed
