### ISSUE TITLE
interactive.py 

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#228]
`python interactive.py`

Import of pycoa successful!
Data from owid isn't allready stored
OWID aka "Our World in Data" database selected ...
Chargement des données OWID : 100%|████████████████████| 404568/404568 [28768.63it/s]
Few information concernant the selected database :  owid
Available key-words, which ∈ ['cur_excess_mortality', 'cur_excess_mortality_cumulative_per_million', 'cur_hosp_patients', 'cur_icu_patients', 'cur_idx_positive_rate', 'cur_reproduction_rate', 'cur_weekly_hosp_admissions', 'total_boosters', 'total_cases', 'total_cases_per_million', 'total_deaths', 'total_deaths_per_million', 'total_gdp_per_capita', 'total_people_fully_vaccinated', 'total_people_fully_vaccinated_per_hundred', 'total_people_vaccinated', 'total_people_vaccinated_per_hundred', 'total_population', 'total_tests', 'total_tests_per_thousand', 'total_vaccinations', 'total_vaccinations_per_hundred']
Example of where :  Curaçao, Bolivia, Plurinational State of, Croatia, Myanmar, Suriname  ...
Last date data  2024-06-10

Traceback (most recent call last):
  File "/Users/noam/Desktop/pycoa/interactive.py", line 15, in <module>
    pycoa.setwhom('owid',reload=False)
  File "/Users/noam/Desktop/pycoa/coa/front.py", line 351, in setwhom
    self._db = coco.DataBase.readpekl('.cache/'+base+'.pkl')
  File "/Users/noam/Desktop/pycoa/coa/covid19.py", line 197, in readpekl
    with open(filepkl, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '.cache/owid.pkl'

**Comment by odadoun** [comment]
fixed
