### ISSUE TITLE
listtile bug 

### ISSUE THREAD

**Issue by NoamXD8** [coa-project/pycoa#229]
`pycoa.listtile()`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[20], line 1
----> 1 pycoa.listtile()

File ~/Desktop/pycoa/coabook/../coa/front.py:265, in Front.listtile(self)
    261 def listtile(self,):
    262     """Return the list of currently avalailable tile option for map()
    263      Default is the first one.
    264     """
--> 265     return self._cocoplot.getallvisu().available_tiles

AttributeError: 'AllVisu' object has no attribute 'getallvisu'

**Comment by odadoun** [comment]
good point Noam ! 
fixed
