### ISSUE TITLE
No tests data available for France in owid db ? 

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#26]
After a 

cf.setwhom('owid')

![Screenshot from 2020-11-30 16-37-12](https://user-images.githubusercontent.com/6871008/100630091-64ef9d00-332a-11eb-9cf1-338796f3499c.png)

**Comment by tjbtjbtjb** [comment]
Seems to be confirmed when filling with 0 NaN values.
```
cf.plot(where='france',which='total_tests',option='fillnan0')
```

**Comment by odadoun** [comment]
As you can see here total_test is not provided for a lot of countries (included France) see https://ourworldindata.org/coronavirus-testing
<img width="908" alt="image" src="https://user-images.githubusercontent.com/11535234/103249348-050f0500-496f-11eb-88d9-b4aa5cd8dd62.png">
