### ISSUE TITLE
Plots and maps should have pycoa and database name printed in

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#29]
Plots and maps should have pycoa and database name printed in

**Comment by tjbtjbtjb** [comment]
Perhaps add the pycoa favicon https://raw.githubusercontent.com/coa-project/coa-project.github.io/main/fig/favicon.ico

**Comment by coa-project** [comment]
Done using a metadata for the main pandas.
Now 'pandas.data_base' return the database name
