### ISSUE TITLE
flags for countries

### ISSUE THREAD

**Issue by coa-project** [coa-project/pycoa#30]
I would be nice to have icons flags available in geo.

https://github.com/linssen/country-flag-icons
https://flag.readthedocs.io/en/latest/
Then we can display it in map for instance

We will  need also flags french department in the case of spf database.
In this case à simple pandas parsing can be used
https://fr.wikipedia.org/wiki/Liste_des_drapeaux_des_r%C3%A9gions_et_territoires_fran%C3%A7ais

Since I have a lot of opened ticket I give it to you :-)

**Comment by tjbtjbtjb** [comment]
Question. It would be easier to have raw data (content of image file) or the URL of a flag ?

**Comment by coa-project** [comment]
Depends of the size ... When we will have the local database functionality with geo stuff we will also get the flags. 
To answer your question may be raw data .

**Comment by tjbtjbtjb** [comment]
svg or png ?

**Comment by coa-project** [comment]
I would say svg if the difference between svg and png is not so important from 
image size point of view

**Comment by coa-project** [comment]
In fact I am pretty convinced that it should be png .

**Comment by tjbtjbtjb** [comment]
In GeoInfo, one can now add field 'flag' also.

**Comment by tjbtjbtjb** [comment]
(in dev branch)
