### ISSUE TITLE
question concernint clist in 

### ISSUE THREAD

**Issue by coa-project** [coa-project/pycoa#33]
in get_stats method (covid19)
I am wondering if you are responsible of those following line (maybe it is me I really don't remember).
This give empty list in the case of opencovid19 ...
============        
clist=list(set(clist)) # to suppress duplicate countries
  
diff_locations = list(set(clist) - set(self.get_locations()))
clist = [i for i in clist if i not in diff_locations]
======

**Comment by tjbtjbtjb** [comment]
Ok. I've identified the problem… which comes from @odadoun lines ☺
Few lines before : 
```
        if self.db != 'spf' and self.db != 'opencovid19':
            self.geo.set_standard('name')
            clist=self.geo.to_standard(clist,output='list',interpret_region=True)
```
This implies that for `opencovid19`, there is not correct standardization of names. 

I do not know the reason for this test for `opencovid19` whereas I can imagine its utility for `spf`. Could you have a look ?

**Comment by coa-project** [comment]
But I don't understant the point
why not using clist ? why this is needed
diff_locations = list(set(clist) - set(self.get_locations())) ??

**Comment by tjbtjbtjb** [comment]
This is to exclude countries which does not exist as real countries. e.g. boats for jhu, or strange areas.

**Comment by coa-project** [comment]
ok  so pertinent only for jhu & owid

**Comment by tjbtjbtjb** [comment]
Perhaps. But you need to do the normalization of the country names anyway.

**Comment by coa-project** [comment]
for sfp and opencovid I will use 'code_subregion'.
Then with geo stuff we will retrieve the good name location

**Comment by tjbtjbtjb** [comment]
I guess it's solved.
