### ISSUE TITLE
Covid19 data for USA

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#36]
The JHU provides data for US, available at `https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series` .
Because in `dev` branch the `GeoCountry` now deals with 'USA', this would be nice to provide detailed US data. This shouldn't need too much work because the data are quite similar as world ones.

**Comment by coa-project** [comment]
should be ok
