### ISSUE TITLE
Log version of hist

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#39]
In hist, the "log" button is for vertical axis, where as one should be interested in log on the x-axis.

**Comment by odadoun** [comment]
Do we need 3 differents button ? normal, log(y), log(x) & log(y) ?

**Comment by tjbtjbtjb** [comment]
Well… 4 would be the best perhaps. Even if log(x) for dates are probably not usefull, it is for hist.
linlin / loglin / linlog / loglog

**Comment by odadoun** [comment]
done ! since bokeh can not support datetime + log , this is only implemented for vertical histo

**Comment by tjbtjbtjb** [comment]
Too bad.
