### ISSUE TITLE
No more data in jhu for USA, Russia, Venezuela, ... ? 

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#40]
No more data in jhu for USA, Russia, Venezuela, ... ? 
See screenshot.
![image](https://user-images.githubusercontent.com/6871008/103235503-a6cc2d00-4942-11eb-8a33-7ff369ff1d88.png)

**Comment by tjbtjbtjb** [comment]
See also : 
![image](https://user-images.githubusercontent.com/6871008/103235568-cbc0a000-4942-11eb-801c-78ad4300d2c9.png)

**Comment by odadoun** [comment]
bug fixed
