### ISSUE TITLE
Bad proportion of bokeh map

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#41]
e.g. when plotting "americas"

See

![image](https://user-images.githubusercontent.com/6871008/103235643-e430ba80-4942-11eb-8b7c-540e8b2b36a7.png)

**Comment by odadoun** [comment]
fixed with tile stuff
<img width="592" alt="image" src="https://user-images.githubusercontent.com/11535234/103481895-e6c95f00-4ddd-11eb-90df-4feda6a88057.png">

**Comment by odadoun** [comment]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/11535234/103481912-0791b480-4dde-11eb-807b-528a13a645f5.png">
