### ISSUE TITLE
When plotting few regions via the where key, add info in the graph ?

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#42]
When plotting few regions, one should prefer to have the information in the title ? e.g. "Europe", "Americas", "Asia", etc.

**Comment by odadoun** [comment]
Do you mean to have this (red stuf)
![image](https://user-images.githubusercontent.com/11535234/116567334-d2b6e980-a907-11eb-95fd-cc699cb635eb.png)

**Comment by tjbtjbtjb** [comment]
well, no.
For example when doing hist with where=['Europe','USA'], should appear as it is, not with expanded interpretation of the region 'Europe'.

**Comment by odadoun** [comment]
Need to use double bracket with option='sumall'
[['Europe'],['USA]]
New feature
