### ISSUE TITLE
Owid data, no hosp info for Germany ? 

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#43]
Owid data, no hosp info for Germany ?

**Comment by odadoun** [comment]
as you can see here
https://ourworldindata.org/covid-hospitalizations
Hosp seems to be not available for Germany
<img width="738" alt="image" src="https://user-images.githubusercontent.com/11535234/103239615-61156180-494e-11eb-8475-990183d65484.png">

**Comment by tjbtjbtjb** [comment]
Ok, good. 
At least, that's not a `pycoa` bug !
