### ISSUE TITLE
Default log output

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#46]
For some data, one could prefer to have directly log version of the plot, without clicking. 

![image](https://user-images.githubusercontent.com/6871008/103236064-0c6ce900-4944-11eb-9c1b-7cb2eeaae1f7.png)

**Comment by odadoun** [comment]
> For some data, one could prefer to have directly log version of the plot, without clicking. 
When you said " For some data" for which exactly ?

**Comment by tjbtjbtjb** [comment]
e.g. the ones with a lot of order of magnitude, e.g. vaccinations currently, see screenshot given.
But this should be an option (perhaps only a `front` option).

**Comment by odadoun** [comment]
done
