### ISSUE TITLE
map with input kwargs does not work anymore

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#47]
See

![image](https://user-images.githubusercontent.com/6871008/103236110-332b1f80-4944-11eb-953b-4a979390b3a5.png)

**Comment by odadoun** [comment]
need to update this example. 
use this z instead
z=cf.get(where='world',which='total_deaths',output='pandas',option='fillnan0',when=':25/12/2020')

**Comment by tjbtjbtjb** [comment]
No need to update the `get` statement. 
The map is working now. 

But when the cursor is over a country, the field is replaced by ??? rather than a value.

**Comment by odadoun** [comment]
Fixed. By default in the map display fillna(0),fillna(method='ffill') is applied to the pandas
