### ISSUE TITLE
GeoInfo.add_field requires geofield. Should add a correct default arg

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#48]
Even when using default pandas output of `pycoa`, the `add_field` method of `GeoInfo` requires to specify `geofield=where`. Should be the default behaviour.

![image](https://user-images.githubusercontent.com/6871008/103236178-708fad00-4944-11eb-89d0-207d5c7e2906.png)

**Comment by odadoun** [comment]
fixed problem was white space in the column name
