### ISSUE TITLE
In spf data, 'rea' with 'nonneg' option creates a RunTimeWarning

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#53]
See screenshot 

![image](https://user-images.githubusercontent.com/6871008/103245788-8fe90300-4961-11eb-82e5-579d96a69871.png)

**Comment by odadoun** [comment]
This is very strange, I have fixed this bug ... moreover ligne 475 from covid19.py is this:
...
    elif o == 'fillnanf':
                pdfiltered[kwargs['which']] = pdfiltered.groupby(['location'])[kwargs['which']].fillna(method='ffill')
            elif o == 'smooth7':
...
Are you sure to use the latested covid19 version ??

**Comment by tjbtjbtjb** [comment]
Yes, definitly, I'm using the very latest `dev` version of `covid19`.

**Comment by tjbtjbtjb** [comment]
And it appears only for `rea`. Not for any other data.

**Comment by odadoun** [comment]
beware 'nonneg' is valid ONLY when 'which' is not a daily value.  It is working when 'which' represents a total value ... How to detect if the variable is a 'total value' or a 'daily value' ? 'total value'  should increase surely but sometime it is decreasing it is the reason why 'nonneg' was invented  ...

**Comment by tjbtjbtjb** [comment]
Two points
- I think, just like https://github.com/coa-project/pycoa/issues/51 , that all variable should be clearly integrated, not daily. Because it's too much confusing. Because variables are not so numerous, for all db, we should provide an integrated version of the data for homogeneity
- There is a bug in the test of the `nonneg` in fact. `s==0` is not properly managed. Reopening the issue.

**Comment by tjbtjbtjb** [comment]
There is a trick to avoid warning. But this does not mean that the output is usefull, because that's true those are 'daily' data. 
Anyway, this issue is solved. Closing.
