### ISSUE TITLE
Map of USA within the jhu-usa db

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#55]
The map of the USA without canada seems strange when using the `jhu-usa` database option. SHould be enhanced.

![image](https://user-images.githubusercontent.com/6871008/103246065-6aa8c480-4962-11eb-97fc-b6d43b505e04.png)

**Comment by odadoun** [comment]
Not easy at all . jhu-usa is belong coge.GeoCountry('USA',True). To have North america one should use g=coge.GeoManager(). To much work and modification inside de code  since folium give what you want

**Comment by odadoun** [comment]
Just have an idea with my coffe. I keep the issue open ...

**Comment by tjbtjbtjb** [comment]
:+1:

**Comment by odadoun** [comment]
should be fixed (why tile stuff)
