### ISSUE TITLE
Currently, in owid, USA data are in advance. Then, nothing appears on maps except USA

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#57]
Currently, in owid, USA data are in advance. Then, nothing appears on maps except USA.

![image](https://user-images.githubusercontent.com/6871008/103246546-1f8fb100-4964-11eb-8b45-93172715a199.png)

**Comment by odadoun** [comment]
I don't know what to do ... we can artificially impose to have at leat 10 countries with non nan values and then automatically change the date ... but it is artificially. I keep the ticket open .

**Comment by tjbtjbtjb** [comment]
If there is a 1 day difference between latest data and others, we could change the last date to one day before. What do you think @odadoun ?

**Comment by tjbtjbtjb** [comment]
Solved now with default fillnan procedure.
