### ISSUE TITLE
Ordering problem in data got from the `get` function ?

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#58]
![image](https://user-images.githubusercontent.com/6871008/103246699-b8263100-4964-11eb-8c3e-e932017187ab.png)

**Comment by odadoun** [comment]
this due to an index problem, this should works
(data[data['where']=='Brazil'].reset_index()['daily']).plot()

**Comment by tjbtjbtjb** [comment]
Well, I think we should add the reset_index in the get method, shouldn't we ? 
De you see @odadoun a reason not to do so ? I tried, it seems to work.

**Comment by odadoun** [comment]
I have no problem with that. if it works add reset_index in the get and close the issue
