### ISSUE TITLE
On graph, the ⓒpycoa.fr does not appear sometimes

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#59]
On graph, the ⓒpycoa.fr does not appear sometimes. It happens more often under `Colab` rather than on my laptop.
This is a strange behaviour !

**Comment by odadoun** [comment]
I have never seen this problem the only explanation I have so fare is the symbol ⓒ ...

**Comment by tjbtjbtjb** [comment]
How is it added, through a javascript ?

**Comment by tjbtjbtjb** [comment]
In dev version, it's written bottom-right now. But it cannot be fully read. See screenshot below.

![image](https://user-images.githubusercontent.com/6871008/104011436-62e0ef80-51ae-11eb-9e10-9e57447a38a9.png)

**Comment by tjbtjbtjb** [comment]
still true…
![image](https://user-images.githubusercontent.com/6871008/104840213-40458980-58c6-11eb-8c54-ebd913e3fe98.png)

**Comment by odadoun** [comment]
After discussion with bokeh developer there is no easy solution , I mean   100%  robust in t
So the good minimal good solution is to shift back to the left .
