### ISSUE TITLE
Cannot plot partial subregion of France anymore ? 

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#61]
Within `pycao` framework using `SPF`.

![image](https://user-images.githubusercontent.com/6871008/103271141-b89ce700-49b9-11eb-96e6-5febe51885c9.png)

**Comment by tjbtjbtjb** [comment]
Probably related to https://github.com/coa-project/pycoa/issues/49

**Comment by odadoun** [comment]
fixed
