### ISSUE TITLE
The smooth7 option induces bad values at the beg of the data plotted

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#62]
see for example 

![image](https://user-images.githubusercontent.com/6871008/103272748-ebe17500-49bd-11eb-95c9-c4c22b4022cb.png)

This was properly managed with the previous version (non pandas). The algo should be reconsidered.

**Comment by tjbtjbtjb** [comment]
But when plotting only 1 country, it does not appear. Index problem ? 

![image](https://user-images.githubusercontent.com/6871008/103273432-97d79000-49bf-11eb-9dde-2d98d9ced0f7.png)

**Comment by odadoun** [comment]
Still nan problem. fixed using fillna(0) after of smooth

**Comment by tjbtjbtjb** [comment]
Not a good way.
Need to understand why this is needed with more than one country, why is not with only one. 
Moreover, it was working with previous version. 
Reopening and keep that issue assigned to @tjbtjbtjb

**Comment by odadoun** [comment]
I think this is a bokeh problem. It appears, I think,  when there are at LEAST 2 countries with NAN values ...can you confirmed and eventually closed

**Comment by tjbtjbtjb** [comment]
Leaving it opened.

**Comment by tjbtjbtjb** [comment]
solved.
