### ISSUE TITLE
RUS.geo.json

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#63]
This is the main problem we have with bokeh map.
Have a look to the json file using by geo:
https://github.com/johan/world.geo.json/blob/master/countries/RUS.geo.json
As you can see Bering strait is on the left part while russia is on the right part. This gives this beautiful map :)
![image](https://user-images.githubusercontent.com/11535234/103358614-4bbb4700-4ab6-11eb-934f-ca01f682414b.png)
An other representation is absolutely needed ...

**Comment by tjbtjbtjb** [comment]
Need to put all points in geometry from Russia at a meridian > 0 rather than < 0. Do you agree ?

**Comment by tjbtjbtjb** [comment]
By the way, a need to do this also for another country ?

**Comment by tjbtjbtjb** [comment]
done.

**Comment by odadoun** [comment]
This problem make me crazy
Here with your modification
![image](https://user-images.githubusercontent.com/11535234/103447072-bde28600-4c86-11eb-80a1-334d16957023.png)
The problem is from bokeh. This the better I've got so far*
![image](https://user-images.githubusercontent.com/11535234/103447079-da7ebe00-4c86-11eb-894d-b94dc95b2a8f.png)
which is good but if you move to the right part 
![image](https://user-images.githubusercontent.com/11535234/103447082-e66a8000-4c86-11eb-83eb-723b5fd4844b.png)

* in term of geo is 
*                             poly=sg.MultiPolygon([sg.Polygon([[x,y] if x<0 else (x,y) for x,y in p.exterior.coords]) for p in poly])

**Comment by tjbtjbtjb** [comment]
There was a modification few minutes ago. Could you try to use the latest version ? 
Anyway, I cannont get your bug. I got the map just below.
![image](https://user-images.githubusercontent.com/6871008/103447338-241cd800-4c8a-11eb-8edd-6c536d47f819.png)
What are the lines of pycoa code you're using ?

**Comment by tjbtjbtjb** [comment]
And for bokeh map… I got 
![image](https://user-images.githubusercontent.com/6871008/103447346-53cbe000-4c8a-11eb-9776-b986e968d82a.png)

**Comment by odadoun** [comment]
Yes I know but this give very bad map most of the time . So I have decided to use tile (not yet update in the current dev version) to have better bokeh country map (https://docs.bokeh.org/en/latest/docs/reference/tile_providers.html)

**Comment by odadoun** [comment]
as you can see for instance with tile you have continent name 
![image](https://user-images.githubusercontent.com/11535234/103447374-d6549f80-4c8a-11eb-8f21-989072fad3a3.png)

**Comment by odadoun** [comment]
you can go to your previous geo version now
