### ISSUE TITLE
HBar plotting with location vertically

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#64]
It would be nice to have such a hbar plot

![image](https://user-images.githubusercontent.com/6871008/103411705-a8c80300-4b71-11eb-895d-8294cf903582.png)

**Comment by odadoun** [comment]
any chance to have a better image resolution ?

**Comment by tjbtjbtjb** [comment]
I think it's done @odadoun ? 
But should be pushed to front too.

**Comment by tjbtjbtjb** [comment]
done. And available in the front (dev version)
