### ISSUE TITLE
GeoCountry and dense_geometry

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#65]
it seems that 
cg.GeoCountry('FRA',dense_geometry=True)
and 
cg.GeoCountry('FRA',dense_geometry=False)

give the same think ...

**Comment by tjbtjbtjb** [comment]
Not at all ! 

![image](https://user-images.githubusercontent.com/6871008/103489500-3aa36a80-4e15-11eb-929a-59eb65c96f5b.png)
