### ISSUE TITLE
Incohérence dans "rad" pour SPF

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#66]
Le champ rad ne semble pas auto-cohérent dans les données SPF. Données du 6 janvier.
- https://dashboard.covid19.data.gouv.fr/ donne 198756 retours à la maison
- tot_rad issu du champ "rad" de spf donne 196006
- l'intégrale de "incid_rad" avec l'offset initial (58664) du 13 mai donne 200120
Par ailleurs comme ces deux dernières grandeurs sont initialisées à la même valeur au 13 mais 2020, on peut noter leur divergence au cours du temps.
![image](https://user-images.githubusercontent.com/6871008/103951962-dbf52e00-513f-11eb-916d-058cfe1fa697.png)

**Comment by odadoun** [comment]
sorry but close I do not thing this is belong to pycoa . But it is true there are  discrepancies. I am still working on it
