### ISSUE TITLE
Should fill the GeoInfo() for World Wide

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#69]
iaits

**Comment by odadoun** [comment]
don't understand really the request  ? if not anymore needed please close

**Comment by tjbtjbtjb** [comment]
that's for me. 
GeoInfo for 'WW' partially filled. Will take some time…

**Comment by tjbtjbtjb** [comment]
The WW aka Worldwide will disappear soon in `dev`. Closing this issue.
