### ISSUE TITLE
Folium not available under colab? 

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#73]
![image](https://user-images.githubusercontent.com/6871008/104782291-429fca80-5784-11eb-852e-12a6dfe55b12.png)

**Comment by odadoun** [comment]
install arial.ttf at the begin of the colab + ask for  0.12.1 folium version

**Comment by tjbtjbtjb** [comment]
What is the command to check and/or install the arial.ttf in the colab notebook ?

**Comment by odadoun** [comment]
!curl -O https://www.freefontspro.com/d/14454/arial.zip
!unzip arial.zip
!cp arial.ttf /usr/share/fonts/Arial.ttf

**Comment by tjbtjbtjb** [comment]
Cannot we put the font file else where ? Is the path tested somewhere in the code ? I'm thinking about updating the setup.py file to install that automatically….

**Comment by odadoun** [comment]
I think it will be nice to have an 'others' folder inside coadata where Arial.ttf could be installed (and other stuff in the futur)

**Comment by tjbtjbtjb** [comment]
True… but we cannot force to install coadata within a colab notebook because it's huge…

**Comment by odadoun** [comment]
Yes but it is only a download area for curl stuff for the precise pb of colab
In the futur we will have a container

**Comment by odadoun** [comment]
this should be fixed
