### ISSUE TITLE
Condensed country name not to be used in popup window when using the cursor

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#75]
e.g. in the graph below, when going onto the first country, we cannot read the full name of the country in the popupwindow (not catched on the screenshot unfortunately).

![image](https://user-images.githubusercontent.com/6871008/104782649-da9db400-5784-11eb-89e2-605a3eda88ff.png)

**Comment by tjbtjbtjb** [comment]
Illustration.

![image](https://user-images.githubusercontent.com/6871008/104809970-cc39b180-57f1-11eb-9f60-0e7d06e577d8.png)

**Comment by odadoun** [comment]
ok fixed
