### ISSUE TITLE
Pbl of color alternance

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#77]
For example, France and Mexico have the same color…

![image](https://user-images.githubusercontent.com/6871008/104813339-d915cf80-5808-11eb-98be-564d6fc88a80.png)

**Comment by odadoun** [comment]
spent to much time on this. I have solved using line_color and a mixe between 3 palette
Paired[10], Set2[8],Set3[12].
Have a look here for palette https://docs.bokeh.org/en/latest/docs/reference/palettes.html
