### ISSUE TITLE
Latest data at different dates

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#84]
When using the `sumall` option, when latest data differs country to country, it may produce negative diff values.

![image](https://user-images.githubusercontent.com/6871008/106203193-4dfae900-61bb-11eb-8fc5-f2bee192a928.png)

Should vbe solved with homogeneous fill of dates and the default `filllna` procedure.

**Comment by odadoun** [comment]
I think this problem is solved now using fill_missing_dates
