### ISSUE TITLE
In map(), the `tile` option not taken into account with folium

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#89]
Should at least provide a warning.

![image](https://user-images.githubusercontent.com/6871008/106206058-c5327c00-61bf-11eb-9bd1-d26e6e6b83da.png)

**Comment by odadoun** [comment]
this should be ok with those pycoa name values: openstreet, positron,esri and stamen
other tile can be add easely (some time folium and bokeh have different behaviour with the same tile)
