### ISSUE TITLE
Almost no help provided for map()

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#93]
e.g. nothing about `visu` ou `tile`

![image](https://user-images.githubusercontent.com/6871008/106207024-5a824000-61c1-11eb-8c32-520eb5b8fc74.png)

**Comment by odadoun** [comment]
Is there a way to get also the inherate docstrings ? help.cf.map should also return docstring from bokeh_map and folium_map  ? (this comment is validate for all the other method)

**Comment by tjbtjbtjb** [comment]
I absolutly don't know…

**Comment by odadoun** [comment]
add some verbose
