### ISSUE TITLE
In spf cannot map dromcom

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#94]
![image](https://user-images.githubusercontent.com/6871008/106207254-bbaa1380-61c1-11eb-860c-dcf2bc209dc2.png)

**Comment by odadoun** [comment]
I have removed the constraint on DOMTOM for boundary calculation see on histo decorator the line domtom=["971","972","973","974","975","976","977","978","984","986","987","988","989"]
  self.boundary = geopdwd.loc[~geopdwd.location.isin(domtom)]['geometry'].total_bounds
