### ISSUE TITLE
Font in Folium !!!!!!!!!!!!!! arhhh

### ISSUE THREAD

**Issue by odadoun** [coa-project/pycoa#96]
'mpl-data/fonts/ttf/DejaVuSans.ttf'
this path doesn't exist in OSX ... 
by the way plt.__file__ return me:

 /usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py
 does it is correct ?

**Comment by tjbtjbtjb** [comment]
Well yes

`'/home/beau/.local/lib/python3.8/site-packages/matplotlib/pyplot.py'` for me.

But what about the output of  `os.path.dirname(plt.__file__)` ? And what is inside this dir ? 

![image](https://user-images.githubusercontent.com/6871008/106271618-14b09080-6230-11eb-8e08-5f845d63d4dd.png)

**Comment by odadoun** [comment]
ok sorry the path and DejaVuSans.ttf is correct.
So I don't understand this behaviour
<img width="235" alt="image" src="https://user-images.githubusercontent.com/11535234/106272267-0fa01100-6231-11eb-91d0-e0050de4013d.png">

**Comment by odadoun** [comment]
ok the pb is the png fabrication
![image](https://user-images.githubusercontent.com/11535234/106272506-76252f00-6231-11eb-9fda-e61a1e5929ba.png)

**Comment by tjbtjbtjb** [comment]
Ok. So the font is ok. Good point.
Under colab or on my own computer, it does not work at all.

![image](https://user-images.githubusercontent.com/6871008/106272741-d320e500-6231-11eb-8f50-d521472de1cc.png)

**Comment by tjbtjbtjb** [comment]
Related to https://github.com/coa-project/pycoa/issues/90

**Comment by odadoun** [comment]
use tile + attr
