### ISSUE TITLE
Bug using nonneg option

### ISSUE THREAD

**Issue by tjbtjbtjb** [coa-project/pycoa#99]
See the screenshot, it appears some negative values. Moreover, the undershoot becomes an overshoot with the nonneg option, what is probably a bug.

![image](https://user-images.githubusercontent.com/6871008/112009965-25da9700-8b27-11eb-8064-0f3b143cb2bc.png)

**Comment by tjbtjbtjb** [comment]
This comes from the data themselves (see below). But pycoa should manage that somehow… 

![image](https://user-images.githubusercontent.com/6871008/112010192-620df780-8b27-11eb-8344-7d8b51d5d191.png)

**Comment by tjbtjbtjb** [comment]
We should fill with NaN if zero values appear for uniformly growing data.
What do you think ? @odadoun

**Comment by odadoun** [comment]
assuming it is ok !
